nome ci - rodar testes

on:[push]

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        mses: actions/checkout@v4

      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: instalar dependencias
        run: pip install -r requeriments.txt

      - name: rodar testes
        run: pytets
      
